version: '3.8'

services:

  web:
    environment:
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_SOCKET_SERVER=wdb
    depends_on:
      - wdb

  worker:
    environment:
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_SOCKET_SERVER=wdb
    depends_on:
      - wdb
    
  wdb:
    image: kozea/wdb:3.2.5
    ports:
      - 1984:1984
